services:
  backend:
    container_name: backend
    build: ./backend
    image: backend
    ports:
      - 8000:8000
    volumes:
      - ./storage:/storage
  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./storage:/storage