name: taller

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: "CI/CD en acción. Ejecutando tareas …"
      
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pandas joblib imblearn

    - uses: actions/checkout@v4        
    - name: Run pytest
      run: pytest --cov=./ --cov-report=xml tests/
  
  comment-success:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Comentar final exitoso
        uses: mshick/add-pr-comment@v2
        with:
          message: "CI/CD terminado con éxito."
